### PR TITLE
feat: dataset enrichment and new layout

### PR DESCRIPTION
**Pull request by shawnyama**
# Description

* new enrichment button/modal
* moved `tera-dataset-description` contents into `tera-dataset` since there is no need to separate them
* will update the column information section's deisgn in another PR since this PR is pretty huge

image

* enriching works, the checkbox for overwriting or not will be handled in a second pass
image

### Testing
- Click the header button "Enrich metadata with AI assistant"
- Enrich the dataset using No document or a document you have in your project
- See if your Column Information is updated

### CODE REVIEW

**Comment by Tom-Szendrey** [comment]
Running into new error (check console for more)
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at new Chart (auto-SSRVGA32.js?v=c202928d:8512:161)
    at primevue_chart.js?v=c202928d:102:25
```

**Comment by mwdchang** [comment]
@shawnyama can you briefly outline the testing procedures for this PR? what are we suppose to look for? What had changed?

**Comment by shawnyama** [comment]
> @shawnyama can you briefly outline the testing procedures for this PR? what are we suppose to look for? What had changed?

These are mainly layout design changes, I added testing instructions to the description

**Review by mwdchang — APPROVED** [review]
I managed to run this as described, but I also got like 50 js errors along the way. Not sure if they are related to the changes or was from before.

**Review by mwdchang — APPROVED** [review]
I managed to run this as described, but I also got like 50 js errors along the way. Not sure if they are related to the changes or was from before.

**Review by dvince2 — APPROVED** [review]

**Pull request merged**
