### PR TITLE
feat: show username in project page; allow user to edit project page

### PR DESCRIPTION
**Pull request by echl**
- Persist username in project when it is created
- Show username in project view
- Allow user to edit project name in project page by clicking on menu and selecting edit
- Formatted date nicely
- Date does not get updated (should be handled by backend?)
- No feedback when inside/outside of editing mode (user can unfocus the text input and be unaware that they are still editing)

https://user-images.githubusercontent.com/16358728/214919649-d7a7368c-25f7-47b6-8fcf-f23266a4173c.mov

https://user-images.githubusercontent.com/16358728/214681844-44cbd54d-7b60-4150-bed7-bcf55c400a23.mov

@YohannParis @jamiewaese-uncharted

### CODE REVIEW

**Comment by YohannParis** [comment]
Could you make the edit part of a `Dropdown` in a 3 vertical dots like on this design please:
https://www.figma.com/file/lOoGAsDwLfMmP3u5qzKHRh/TERArium-HMI-Designs---PrimeVue-version?node-id=8594%3A56537&t=8uTBA5DUp2FuTuW0-4

Sorry, I asked @jamiewaese-uncharted to do something for that task, and I forgot to send it to you.
I like the idea of editing the name right there, but I'm not sure it should be done on a click on the name. Like, when you click on the three dots, select `Edit name` in the dropdown, activate your feature with a focus border on the name.

Does that make sense?

**Comment by echl** [comment]
> Could you make the edit part of a `Dropdown` in a 3 vertical dots like on this design please: https://www.figma.com/file/lOoGAsDwLfMmP3u5qzKHRh/TERArium-HMI-Designs---PrimeVue-version?node-id=8594%3A56537&t=8uTBA5DUp2FuTuW0-4
> 
> Sorry, I asked @jamiewaese-uncharted to do something for that task, and I forgot to send it to you. I like the idea of editing the name right there, but I'm not sure it should be done on a click on the name. Like, when you click on the three dots, select `Edit name` in the dropdown, activate your feature with a focus border on the name.
> 
> Does that make sense?

Makes sense and can do!

**Review by dvince2 — APPROVED** [review]
LGTM!

**Review by YohannParis — APPROVED** [review]
Looks good to me.

**Pull request merged**
