### PR TITLE
Update to gradle 8

### PR DESCRIPTION
**Pull request by bigglesandginger**
# Description

* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.

Resolves #(issue)

### CODE REVIEW

**Review by YohannParis — APPROVED** [review]
Works on my local

**Comment by dvince2** [comment]
@chris-dickson what was the issue pantera had with java 21? Was it the java formatter?

**Comment by chris-dickson** [comment]
> @chris-dickson what was the issue pantera had with java 21? Was it the java formatter?

Yes.  It doesn't work well on the new Java 21 features.

**Comment by YohannParis** [comment]
> > @chris-dickson what was the issue pantera had with java 21? Was it the java formatter?
> 
> Yes. It doesn't work well on the new Java 21 features.

Works on us.

Screenshot 2024-07-17 at 15 58 43
e new Java 21 features.

**Review by dvince2 — APPROVED** [review]
Approving, but lets not merge until after the demo has happened?

**Pull request merged**
