### PR TITLE
feat: replace logo with icon

### PR DESCRIPTION
**Pull request by YohannParis**
# Description

* Replace the logo with an icon + name of the project on a project page
* Simplify the navbar
* Clear the search bar if not on the Data Explorer page

video

### CODE REVIEW

**Review by Tom-Szendrey — DISMISSED** [review]

**Review by dvince2 — DISMISSED** [review]

**Review by tangopapatime — APPROVED** [review]

**Review by echl — APPROVED** [review]
Looks good to me! Though the bold text on the dropdown menu looks a bit off to me, personally.

**Comment by tangopapatime** [comment]
The issue does what it says :) but I think it looks kind of "off" to me.  Maybe @jamiewaese-uncharted might have some thoughts?

**Comment by tangopapatime** [comment]
> Looks good to me! Though the bold text on the dropdown menu looks a bit off to me, personally.

Our usage of "off" were independent of each other :P

**Comment by YohannParis** [comment]
I did'n thought that this PR would be so controversial.

**Review by echl — APPROVED** [review]

**Pull request merged**
