### PR TITLE
Added @Param annotation to `ProjectRepository.java#findByIdsWithAssets` 

### PR DESCRIPTION
**Pull request by jryu01**
# Description

I was getting following error
```
2024-07-11 10:48:15 [ERROR] Error retrieving projects from postgres db [software.uncharted.terarium.hmiserver.controller.dataservice.ProjectController:172] org.springframework.dao.InvalidDataAccessApiUsageException: For queries with named parameters you need to provide names for method parameters; Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:368) at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:234) at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550) at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:243) at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:244) at jdk.proxy3/jdk.proxy3.$Proxy272.findByIdsWithAssets(Unknown Source) at software.uncharted.terarium.hmiserver.service.data.ProjectService.getActiveProjects(ProjectService.java:52)
```
It looks like Spring Data JPA doesn't recognize the param `ids` and fails to pass the param to the custom query. 
Adding `@Param("ids")` annotation seems to fix the issue.

Also I updated the gollm version to the latest version. 

Resolves #(issue)

### CODE REVIEW

**Comment by bigglesandginger** [comment]
What Java version are you using?  As Gauldie, myself, and the deployments do not seem to have this problem.  Though if this fixes this... I will test locally

**Review by YohannParis — APPROVED** [review]

**Comment by jryu01** [comment]
@bigglesandginger Looks like java version I'm using is 17 and I'm running the server using VsCode

**Comment by YohannParis** [comment]
> @bigglesandginger Looks like the java version I'm using is 17 and I'm running the server using VsCode

VSCode, does not run Java properly with Graddle. You should run via the command line.

**Comment by jryu01** [comment]
> VSCode, does not run Java properly with Graddle. You should run via the command line.

I debug with VsCode

**Review by dvince2 — APPROVED** [review]

**Review by bigglesandginger — APPROVED** [review]

**Pull request merged**
