### PR TITLE
feat: remove mock-data-service

### LINKED ISSUE #282: Remove `mock-data`service
When the `data-service` is up and running within TERArium k8 cluster:
 
- [ ] Make sure that all endpoints handled by `mock-data-service` are fullfilled by the `data-service`.
- [ ] Delete `mock-data-service` from the `terarium` repo.
- [ ] Delete all references in the makefile and docker bake file.
- [ ] Remove the associated deployment scripts from the `orchestration` repo.

### PR DESCRIPTION
**Pull request by YohannParis**
# Description

The _Data Service_ is up an functional, now it is time to say farewell to our _Mock Data Service_.

Resolve #282

### CODE REVIEW

**Review by dvince2 — DISMISSED** [review]

**Comment by YohannParis** [comment]
Thank you  @dvince2 
I rebase which branch this PR should go to, to avoid conflict with @dgauldie task of rerouting to the real _Data Service_

**Review by dvince2 — APPROVED** [review]
Ah true! Approved again.

**Comment by dgauldie** [comment]
I fixed the problem with the lint checking in my PR. Once mine is in, the checks should work

**Review by dvince2 — APPROVED** [review]

**Review by dgauldie — APPROVED** [review]
LGTM

**Pull request merged**
