### PR TITLE
clean: remove explorer

### PR DESCRIPTION
**Pull request by shawnyama**
# Description

* Delete all components, services and type files related to the DataExplorer
* I removed the facets package as well

Resolves #(issue)

### CODE REVIEW

**Review by YohannParis — APPROVED** [review]
LGTM, thank you for the cleanup

**Comment by mwdchang** [comment]
@shawnyama @YohannParis Is this covering the clean up server-side as well? or is separate?

**Comment by shawnyama** [comment]
> @shawnyama @YohannParis Is this covering the clean up server-side as well? or is that separate?

I was just about to investigate if it's worth saving for another PR. I'll see - if it's not much more I'll do it.

**Comment by shawnyama** [comment]
I am gonna branch of this branch and attempt to remove backend stuff

**Review by mwdchang — APPROVED** [review]

**Pull request merged**
