### PR TITLE
Jamie adjust petrinet transition matrix rectangle widths

### PR DESCRIPTION
**Pull request by jamiewaese-uncharted**
This is something Pascale asked me to look into a while back. Finally figured it out. @mwdchang you may want to make sure I didn't break anything... but it looks good here. 

**BEFORE**
Monosnap Terarium 2024-03-21 19-42-40

**AFTER**
image

### CODE REVIEW

**Comment by mwdchang** [comment]
@jamiewaese-uncharted there are a couple matrix configurations that look a little odd.

image

**Comment by mwdchang** [comment]
Also note the notation we use is `#-rows X #-columns`, your before picture had the numbers flipped  ... I am assuming that is just a typo and we don't actually want to calculate the matrix-transpose?

**Comment by jamiewaese-uncharted** [comment]
- Fixed the issue you noted above, when rows are greater than cols
- Removed the labels. They were too small to be useful and added clutter. 
- Removed the border-radiuses 

image

**Comment by jamiewaese-uncharted** [comment]
fyi
image

image

**Comment by YohannParis** [comment]
@mwdchang I fixed the last errors. Do you mind giving it a review please?

**Review by mwdchang — APPROVED** [review]

**Pull request merged**
