### PR TITLE
chore(theme): remove fontawesome dependency and replace with IBM icons

### LINKED ISSUE #64: Remove FontAwesome
- [x] Replace all instance of FontAwesome Icons with IBM Carbon Icons
- [ ] Remove FontAwesome depencies

### PR DESCRIPTION
**Pull request by shawnyama**
# Description

I replaced all the fontawesome icons with IBM icons. One issue I need a little assistance on is getting rid of these dependencies found in the `yarn.lock`:

image

The only one I got rid of properly was the one named `fontawesome-free`. It's gone from the `package.json` in `/webapp` and the `yarn.lock`. These other ones I can't get rid of using yarn remove - they are only found in the `yarn.lock` not in any other `package.json`. I also tried doing another `yarn install` but they are still there. I am kinda doubting that it's appropriate to just erase these lines from the `yarn.lock`.

Resolves #64 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide reproduction instructions and list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by YohannParis** [comment]
> The only one I got rid of properly was the one named fontawesome-free. It's gone from the package.json in /webapp and the yarn.lock. These other ones I can't get rid of using yarn remove - they are only found in the yarn.lock not in any other package.json. I also tried doing another yarn install but they are still there. I am kinda doubting that it's appropriate to just erase these lines from the yarn.lock.

It is because it is imported by _Facets_. So don't worry, as long as you removed it from our own code.

**Comment by Nithos** [comment]
You should not be modifying the lock file manually (99.9% of the time). The Yarn install should be updating that file automatically and in the rare cases due to big changes you can remove the lock file completely and then have it regenerated by yarn on install again.

**Review by YohannParis — DISMISSED** [review]
Well done!
I love the light touch cleaning/renaming here and there. Please keep doing it, this is your codebase as well now!

**Review by YohannParis — APPROVED** [review]
Fixed the `yarn.lock`!

**Pull request merged**
