### PR TITLE
style: add terarium theme for keycloak login

### LINKED ISSUE #26: Re-design keycloack login page

### PR DESCRIPTION
**Pull request by Nithos**
# Description

Initial Keycloak theme for Terarium. Theme is loaded and selected upon startup (as per configuration in the Kubernetes deployment files). Refer to the README file for details on how to update/change the styling as needed.

NOTE: Initial Kubernetes startup might be slightly longer 
NOTE: Currently still using internal docker repository so only accessible within 

Resolves #26 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Visually verified local deployment

## To test

1.     Make sure you k8s stack is down i.e ./gateway.sh down
2.     Check out this branch
3.     Start the stack up again ./gateway.sh up
4.     Make sure that all pods are running and completed their init (kubectl get pods)
5.     Start the rest of the application and go to the login screen
6.     Should see Terarium themed login now

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mwdchang** [comment]
works fine for me!

**Review by mwdchang — APPROVED** [review]

**Comment by bencodrington** [comment]
Is this screen supposed to look different?

image

I'm unclear on how to properly test this PR.

**Comment by Nithos** [comment]
@bencodrington yes that is supposed to look different.
To test
1. Make sure you k8s stack is down i.e `./gateway.sh down`
2. Check out this branch
3. Start the stack up again `./gateway.sh up`
4. Make sure that all pods are running and completed their init (kubectl get pods)
5. Start the rest of the application and go to the login screen
6. Should see Terarium themed login now

image

**Comment by bencodrington** [comment]
> @bencodrington yes that is supposed to look different. To test
> 
> 1. Make sure you k8s stack is down i.e `./gateway.sh down`
> 2. Check out this branch
> 3. Start the stack up again `./gateway.sh up`
> 4. Make sure that all pods are running and completed their init (kubectl get pods)
> 5. Start the rest of the application and go to the login screen
> 6. Should see Terarium themed login now
> 
> image

Appreciate it! This worked. We may wish to add a quick note in one of the READMEs about using these commands to restart the k8s stack in case of future changes to the theme.

**Review by bencodrington — APPROVED** [review]

**Comment by Nithos** [comment]
> > @bencodrington yes that is supposed to look different. To test
> > 
> > 1. Make sure you k8s stack is down i.e `./gateway.sh down`
> > 2. Check out this branch
> > 3. Start the stack up again `./gateway.sh up`
> > 4. Make sure that all pods are running and completed their init (kubectl get pods)
> > 5. Start the rest of the application and go to the login screen
> > 6. Should see Terarium themed login now
> > 
> > image
> 
> Appreciate it! This worked. We may wish to add a quick note in one of the READMEs about using these commands to restart the k8s stack in case of future changes to the theme.

Added additional documentation to the readme

**Review by bencodrington — APPROVED** [review]

**Review by YohannParis — APPROVED** [review]

**Pull request merged**
