### PR TITLE
fix: asset selection in project page

### PR DESCRIPTION
**Pull request by shawnyama**
# Description

We should avoid conditionally rendering `<AccordionTab>`s. The `active-tab` prop in `<Accordion>` expects all the tabs specified in it to be rendered. If they are not rendered the component breaks - which breaks switching assets. See the [video](https://github.com/DARPA-ASKEM/terarium/issues/2027).

In order to hide empty accordion tabs I added a css rule which applies `display: none` if the tab empty. The rule uses the `has` property which is properly supported in Chromium based browsers. Firefox users may still see an AccordionTab without any content.

Feel free to use `v-if` inside the scope `<AccordionTab>` but not on the component itself: 
`<AccordionTab v-if="condition that ruins things">`

### CODE REVIEW

**Comment by mwdchang** [comment]
Tagging @Tom-Szendrey here, since he was fixing a problem along the same areas where the collapsed accordions created an update problem.

**Comment by shawnyama** [comment]
Noticing that `tera-external-publications.vue` has the warn error related to the Accordion. Can't narrow this one down. Asset switching doesn't break in the video but it did happen to me once when switching through publications

https://github.com/DARPA-ASKEM/terarium/assets/28237258/48b27a61-3ab0-4a4e-838d-e616137d83e2

**Comment by Tom-Szendrey** [comment]
I had a similar issue that was to do with the accordion not correctly updating upon opening an accordion tab
`tera-model-editor` would generate a renderer based off of a closed accordion tab and have a width + height = 0. When the tab was reopened it would not retrigger this. 
On the Accordion level I added `v-bind:lazy="true"`

could a similar solution be used here?

If v-if is an issue inside accordiontab we should raise this in hmi chat so it wont be as commonly done

**Comment by shawnyama** [comment]
Update:

After chatting with @Tom-Szendrey I want to try out rerendering the component. For example when switching from one `tera-model.vue` to another it should reload the component instead of populating the same one with different data. A rerender may fix this.

 The CSS rule forces us to work with AccordionTabs in a specific way which is not really sustainable. 
 
 Also I am not coming across these Accordion related errors that is breaking the asset switching anymore... did something change?

**Pull request closed without merging**
