### PR TITLE
feat: setup base css

### PR DESCRIPTION
**Pull request by YohannParis**
* Added the favicon from the temporary logo
* Move the stylesheet outside of Vue project
* Added [design-tokens](https://github.com/unchartedsoftware/design-tokens)
* Added IBM Plex font family (Sans & Mono)
* Added IBM Carbon Icons for Vue
* Added **Temporary** TERArium logo

### CODE REVIEW

**Comment by mwdchang** [comment]
It feels like the borders are creating weird illusions, like something is misaligned. It is more evident on the red-button than other colours. Anyone else feel this way?


image

**Comment by YohannParis** [comment]
> It feels like the borders are creating weird illusions, like something is misaligned. It is more evident on the red-button than other colours. Anyone else feel this way?

I just applied the notifications colours to the buttons have a starting point.
There is a lot of CSS that needs to be imported from Tellfinder, but I needed to start adding the design tokens first.

**Comment by bencodrington** [comment]
image

Logo doesn't seem to be loading for me. Is that expected?

**Comment by Nithos** [comment]
recommend adding an alias for assets 
will fix the failing test

**Comment by YohannParis** [comment]
> I was about to suggest removing the extra font files, but it looks like you're way ahead of me! :)
> 
> Other than the logo issue I flagged above, this looks good to me! Thanks.
> 
> Just want to confirm that you're not opposed to having component-specific styles live within the component.vue files themselves, right? It's just the global stylesheets that you wanted to move to the assets directory?

Exactly!

That's why I created a basic `Button.vue` component to show that the design-tokens, and global CSS are fine as an assets. Also to demonstrate the IBM Carbon icons

**Review by mwdchang — APPROVED** [review]

**Review by bencodrington — APPROVED** [review]
Looks good! Thanks

**Review by shawnyama — APPROVED** [review]

**Pull request merged**
